import SwiftUI

// Generated by Supernova - do not modify manually
public extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {

        // Primary brand

        /// Color principal de la marca
        public let primaryBrandColorBrand800 = Color(.sRGB, red: 76/255, green: 182/255, blue: 158/255, opacity: 1) 
    }
}